# Generated by Django 4.2.1 on 2023-05-20 22:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_inostri', '0002_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=128),
        ),
    ]
