# Generated by Django 4.2.1 on 2023-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_inostri', '0003_alter_articulo_cuerpo_alter_articulo_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
