# Generated by Django 4.2.1 on 2023-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inostri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varietal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='varietal',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
