# Generated by Django 4.2.1 on 2023-05-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inostri', '0002_remove_varietal_tipo_varietal_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='region',
            new_name='zona',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='region',
            new_name='zona',
        ),
    ]
