# Generated by Django 4.2.1 on 2023-05-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inostri', '0004_alter_varietal_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietal',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
